
name: First Workflow
on: 
  push:
    branches:
      - main
jobs:
  run-shell-command:
    runs-on : ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello, World!"
      - name: Multiline command
        run: |
          node -v
          npm -v
          echo "This is line 1"
          echo "This is line 2"
